#!/bin/sh --
tty=$(tty)
tty=${tty#/dev/tty}

runtimedir=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}

export XAUTHORITY="${XAUTHORITY:-$runtimedir/xauthority}"
export DISPLAY=:"$tty"

touch -- "$XAUTHORITY"

xauth add :"$tty" MIT-MAGIC-COOKIE-1 "$(od -An -N16 -tx /dev/urandom | tr -d ' ')"

dbus-update-activation-environment DISPLAY XAUTHORITY
dinitctl setenv DISPLAY XAUTHORITY

Xorg :"$tty" -keeptty vt"$tty" -noreset -auth "$XAUTHORITY" -displayfd "$DINIT_READYFD"
xauth remove :"$tty"
