#!/bin/sh
bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width          1
bspc config window_gap            3
bspc config split_ratio           0.5
bspc config removal_adjustment    false
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config click_to_focus        button1

bspc rule -a Firefox desktop=^2
bspc rule -a mpv state=floating
bspc rule -a Peek state=floating
bspc rule -a kittyfloat state=floating
bspc rule -a TelegramDesktop desktop=^3
bspc rule -a Hexchat desktop=^3
bspc rule -a Ripcord desktop=^3
bspc rule -a Steam desktop=^4 state=floating
