#!/bin/sh
bspc monitor DisplayPort-1 -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width          1
bspc config window_gap            3
bspc config split_ratio           0.5
bspc config removal_adjustment    false
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config click_to_focus        button1

bspc rule -a floorp desktop=1
bspc rule -a TelegramDesktop desktop=2
bspc rule -a discord desktop=2
bspc rule -a vesktop desktop=2
bspc rule -a moonlight-stable desktop=2
bspc rule -a steam desktop=3
bspc rule -a qimgv state=floating
bspc rule -a mpv state=floating
bspc rule -a kittyfloat state=floating
bspc rule -a vicinae border=off
bspc rule -a lxqt-openssh-askpass state=floating
