#!/bin/sh
XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.local/state
XDG_CACHE_HOME=$HOME/.local/cache
XDG_CONFIG_HOME=$HOME/.local/etc
GOPATH=$XDG_DATA_HOME/go
CARGO_HOME=$XDG_DATA_HOME/cargo
GRADLE_USER_HOME=$XDG_DATA_HOME/gradle

PATH=$HOME/.local/bin:$HOME/.nimble/bin:$CARGO_HOME/bin:$GOPATH/bin:$PATH

EDITOR=kak
VISUAL=kak
PAGER=kak
MANPAGER=kak

GNUPGHOME=$XDG_DATA_HOME/gnupg
GPG_TTY=$(tty)
NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
RUSTUP_HOME=$XDG_DATA_HOME/rustup

export \
 XDG_DATA_HOME XDG_CACHE_HOME XDG_CONFIG_HOME XDG_STATE_HOME EDITOR VISUAL GOPATH CARGO_HOME \
 RUSTUP_HOME PATH GPG_TTY GNUPGHOME NPM_CONFIG_USERCONFIG GRADLE_USER_HOME PAGER MANPAGER

systemctl --user import-environment \
 XDG_DATA_HOME XDG_CACHE_HOME XDG_CONFIG_HOME XDG_STATE_HOME EDITOR VISUAL GOPATH CARGO_HOME \
 RUSTUP_HOME PATH GPG_TTY GNUPGHOME NPM_CONFIG_USERCONFIG GRADLE_USER_HOME PAGER MANPAGER
