# Kakoune plugins

["https://github.com/alexherbo2/auto-pairs.kak"]
files = ["rc/auto-pairs.kak"]

["https://github.com/alexherbo2/connect.kak"]

["https://github.com/alexherbo2/prelude.kak"]
files = ["rc/prelude.kak", "rc/prelude.sh"]

["https://github.com/alexherbo2/search-highlighter.kak"]
files = ["rc/search-highlighter.kak"]

["https://github.com/alexherbo2/replace.kak"]
files = ["rc/replace-mode.kak"]

["https://github.com/alexherbo2/word-select.kak"]
files = ["rc/word-select.kak"]

["https://github.com/alexherbo2/explore.kak"]
files = ["rc/explore/files.kak", "rc/explore/buffers.kak"]

["https://github.com/Delapouite/kakoune-auto-percent"]
files = ["auto-percent.kak"]

["https://github.com/Delapouite/kakoune-text-objects"]
files = ["text-objects.kak"]

["https://github.com/Delapouite/kakoune-cd"]
files = ["cd.kak"]

["https://github.com/Delapouite/kakoune-buffers"]
files = ["buffers.kak"]

["https://github.com/occivink/kakoune-expand"]
files = ["expand.kak"]

["https://github.com/occivink/kakoune-sudo-write"]
files = ["sudo-write.kak"]

["https://github.com/occivink/kakoune-find"]
files = ["find.kak"]

["https://github.com/occivink/kakoune-gdb"]
files = ["gdb.kak", "gdb-output-handler.perl"]

["https://github.com/occivink/kakoune-vertical-selection"]
files = ["vertical-selection.kak"]

["https://github.com/occivink/kakoune-sort-selections"]
files = ["sort-selections.kak"]

["https://gitlab.com/notramo/elvish.kak"]
files = ["elvish.kak"]

["https://github.com/andreyorst/smarttab.kak"]
files = ["rc/smarttab.kak"]

["https://github.com/chambln/kakoune-readline"]
files = ["readline.kak"]

["https://github.com/lenormf/kakoune-extra"]
files = ["widgets/git-branch.kak", "vcs.kak"]

["https://gitlab.com/Screwtapello/kakoune-state-save"]
files = ["state-save.kak"]

["https://github.com/JJK96/kakoune-repl-send"]
files = ["repl.kak"]

# mpv plugins

["https://github.com/ekisu/mpv-webm"]
files = ["build/webm.lua"]

["https://github.com/mpv-player/mpv"]
files = ["TOOLS/lua/autoload.lua"]

["https://github.com/rossy/mpv-repl"]
files = ["repl.lua"]

["https://github.com/mfcc64/mpv-scripts"]
files = ["visualizer.lua"]
