# Kakoune plugins

["https://github.com/Delapouite/kakoune-auto-percent"]
files = ["auto-percent.kak"]

["https://github.com/Delapouite/kakoune-text-objects"]
files = ["text-objects.kak"]

["https://github.com/Delapouite/kakoune-cd"]
files = ["cd.kak"]

["https://github.com/Delapouite/kakoune-buffers"]
files = ["buffers.kak"]

["https://github.com/occivink/kakoune-sudo-write"]
files = ["sudo-write.kak"]

["https://github.com/occivink/kakoune-find"]
files = ["find.kak"]

["https://github.com/occivink/kakoune-buffer-switcher"]
files = ["buffer-switcher.kak"]

["https://github.com/occivink/kakoune-gdb"]
files = ["gdb.kak", "gdb-output-handler.perl"]

["https://github.com/occivink/kakoune-vertical-selection"]
files = ["vertical-selection.kak"]

["https://github.com/occivink/kakoune-sort-selections"]
files = ["sort-selections.kak"]

["https://github.com/andreyorst/smarttab.kak"]
files = ["rc/smarttab.kak"]

["https://github.com/chambln/kakoune-readline"]
files = ["readline.kak"]

["https://gitlab.com/Screwtapello/kakoune-state-save"]
files = ["state-save.kak"]

["https://gitlab.com/Screwtapello/kakoune-mark-show"]
branch = "main"
files = ["mark-show.kak"]

["https://gitlab.com/Screwtapello/kakoune-repl-buffer"]
files = ["repl-buffer.kak", "repl-buffer-input"]

["https://github.com/kakoune-editor/kakoune-extra-filetypes"]
files = ["rc/glsl.kak"]

["https://github.com/listentolist/kakoune-fandt"]
files = ["fandt.kak"]

["https://github.com/harryoooooooooo/diff.kak"]
branch = "main"
files = ["rc/diff.kak"]

# mpv plugins

["https://github.com/rossy/mpv-repl"]
files = ["repl.lua"]

["https://github.com/mfcc64/mpv-scripts"]
files = ["visualizer.lua"]

["https://github.com/Eisa01/mpv-scripts"]
files = ["scripts/UndoRedo.lua", "scripts/SmartCopyPaste.lua"]
