#:schema https://yazi-rs.github.io/schemas/theme.json

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

[tabs]
active = { fg = "black", bg = "blue", bold = true }
inactive = { fg = "cyan", bg = "reset" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[indicator]
padding = { open = "█", close = "█" }

[git]
modified_sign = " "
untracked_sign = " "
added_sign = " "

[icon]
prepend_exts = [
  { name = "ttf", text = "" },
  { name = "ttc", text = "" },

  { name = "nim", text = "", fg = "yellow" },
  { name = "nims", text = "", fg = "yellow" },
  { name = "nimble", text = "", fg = "yellow" },
  { name = "elv", text = "󰯂", fg = "green" },

  { name = "nsp", text = "󰟡", fg = "red" },
  { name = "xci", text = "󰟡", fg = "red" },

  { name = "chd", text = "", fg = "#d0bec8" },
  { name = "rvz", text = "", fg = "#d0bec8" },

  { name = "dwarfs", text = "", fg = "red" },
  { name = "zpaq", text = "", fg = "red" },

]

prepend_globs = [
  { url = "*/rom/nes/", text = "󰺵", fg = "white" },
  { url = "*/rom/snes/", text = "󰊗", fg = "white" },
  { url = "*/rom/gb/", text = "󱎓", fg = "white" },
  { url = "*/rom/gbc/", text = "󱎓", fg = "white" },
  { url = "*/rom/gba/", text = "󱎓", fg = "white" },
  { url = "*/rom/ps2/", text = "", fg = "blue" },
  { url = "*/rom/ps3/", text = "", fg = "blue" },
  { url = "*/rom/psp/", text = "", fg = "blue" },
  { url = "*/rom/psx/", text = "", fg = "blue" },
  { url = "*/rom/psx-multidisk/", text = "", fg = "blue" },
  { url = "*/rom/switch/", text = "󰟡", fg = "red" },
  { url = "*/rom/wii/", text = "󰖫", fg = "white" },
  { url = "*/rom/wiiu/", text = "󰜭", fg = "blue" },
  { url = "*/rom/xbox/", text = "", fg = "green" },
  { url = "*/rom/xbox360/", text = "", fg = "green" },
]
