#!/bin/sh
xrandr --output DisplayPort-1 --primary
xrandr --output HDMI-A-0 --auto --left-of DisplayPort-1

xset s off
xset -dpms
xrdb -nocpp "$XDG_CONFIG_HOME/X11/xresources" &
xsetroot -cursor_name left_ptr &
xkbcomp "$HOME/dot/layout.xkb" "$DISPLAY" &
wlp
