#!/bin/sh
xrandr --output DisplayPort-1 --primary

xset s off
xset -dpms
xrdb -nocpp "$XDG_CONFIG_HOME/X11/xresources" &
xsetroot -cursor_name left_ptr &
xkbcomp "$HOME/dot/layout.xkb" "$DISPLAY" &
wlp
